---
  title: "Linear Mixed Model"
author: "AliyaLakhani"
date: "12/15/2023"
output: 
  md_document:
  variant: gfm
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/tmp')
```

```{r}

library("lme4")
library("lmerTest")
library("nlme")
library("ggplot2")
library("performance")

```

```{r}
#Figure 1d LME (Donor Random)

#Load file
data1<- read.csv("~/Figure1d.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(Growth~ Donor + CAR, data=data1)
summary(model)

model <- lmer(Growth~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 2b glucose LME (Donor Random)

#Load file
data1<- read.csv("~/Figure2b.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(glucose~ Donor + CAR, data=data1)
summary(model)

model <- lmer(glucose~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 2b lactate LME (Donor Random)

#Load file
data1<- read.csv("~/Figure2b.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(lactate~ Donor + CAR, data=data1)
summary(model)

model <- lmer(lactate~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 3b LME (Donor Random)

#Load file
data1<- read.csv("~/Figure3bc.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(glutamate~ Donor + CAR, data=data1)
summary(model)

model <- lmer(glutamate~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 3c LME (Donor Random)

#Load file
data1<- read.csv("~/Figure3bc.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(alanine~ Donor + CAR, data=data1)
summary(model)

model <- lmer(alanine~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 5a LME (Donor Random)

#Load file
data1<- read.csv("~/Figure5a.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(ammonia~ Donor + CAR, data=data1)
summary(model)

model <- lmer(ammonia~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 5e EGFRt LME (Donor Random)

#Load file
data1<- read.csv("~/Figure5eEGFRt.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$Media <- relevel(data1$Media, ref = "dFBS")

#model data and add optimizer 
model.matrix(~Donor + Media, data=data1, Media=dFBS)
model <- lm(Growth~ Donor + Media, data=data1)
summary(model)

model <- lmer(Growth~ (1|Donor) + Media, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))
```

```{r}
#Figure 5e CD19 LME (Donor Random)

#Load file
data1<- read.csv("~/Figure5eCD19.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$Media <- relevel(data1$Media, ref = "dFBS")

#model data and add optimizer 
model.matrix(~Donor + Media, data=data1, Media=dFBS)
model <- lm(Growth~ Donor + Media, data=data1)
summary(model)

model <- lmer(Growth~ (1|Donor) + Media, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 5e Leu16 LME (Donor Random)

#Load file
data1<- read.csv("~/Figure5eLeu16.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$Media <- relevel(data1$Media, ref = "dFBS")

#model data and add optimizer 
model.matrix(~Donor + Media, data=data1, Media=dFBS)
model <- lm(Growth~ Donor + Media, data=data1)
summary(model)

model <- lmer(Growth~ (1|Donor) + Media, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 5e Rituximab LME (Donor Random)

#Load file
data1<- read.csv("~/Figure5eRituximab.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$Media <- relevel(data1$Media, ref = "dFBS")

#model data and add optimizer 
model.matrix(~Donor + Media, data=data1, Media=dFBS)
model <- lm(Growth~ Donor + Media, data=data1)
summary(model)

model <- lmer(Growth~ (1|Donor) + Media, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 5e RFR-LCDR LME (Donor Random)

#Load file
data1<- read.csv("~/Figure5eRFRLCDR.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$Media <- relevel(data1$Media, ref = "dFBS")

#model data and add optimizer 
model.matrix(~Donor + Media, data=data1, Media=dFBS)
model <- lm(Growth~ Donor + Media, data=data1)
summary(model)

model <- lmer(Growth~ (1|Donor) + Media, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 6f LME (Donor Random)

#Load file
data1<- read.csv("~/Figure6f.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(Growth~ Donor + CAR, data=data1)
summary(model)

model <- lmer(Growth~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 6g lactate LME (Donor Random)

#Load file
data1<- read.csv("~/Figure6g.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(lactate~ Donor + CAR, data=data1)
summary(model)

model <- lmer(lactate~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 6g alanine LME (Donor Random)

#Load file
data1<- read.csv("~/Figure6g.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(alanine~ Donor + CAR, data=data1)
summary(model)

model <- lmer(alanine~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 6g glutamate LME (Donor Random)

#Load file
data1<- read.csv("~/Figure6g.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(glutamate~ Donor + CAR, data=data1)
summary(model)

model <- lmer(glutamate~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Figure 6g ammonia LME (Donor Random)

#Load file
data1<- read.csv("~/Figure6g.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(ammonia~ Donor + CAR, data=data1)
summary(model)

model <- lmer(ammonia~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 3a FBP LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure3abc.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(FBP~ Donor + CAR, data=data1)
summary(model)

model <- lmer(FBP~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 3b citrate LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure3abc.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(citrate~ Donor + CAR, data=data1)
summary(model)

model <- lmer(citrate~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 3b aKG LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure3abc.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(aKG~ Donor + CAR, data=data1)
summary(model)

model <- lmer(aKG~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 3b fumarate LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure3abc.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(fumarate~ Donor + CAR, data=data1)
summary(model)

model <- lmer(fumarate~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 3b malate LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure3abc.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(malate~ Donor + CAR, data=data1)
summary(model)

model <- lmer(malate~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 3c ATP/ADP LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure3abc.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(ATPADP~ Donor + CAR, data=data1)
summary(model)

model <- lmer(ATPADP~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 3c GSH/GSSG LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure3abc.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(GSHGSSG~ Donor + CAR, data=data1)
summary(model)

model <- lmer(GSHGSSG~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 3c NADH/NAD LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure3abc.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(NADHNAD~ Donor + CAR, data=data1)
summary(model)

model <- lmer(NADHNAD~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 3d Lac/Glc LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure3de.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(lacglc~ Donor + CAR, data=data1)
summary(model)

model <- lmer(lacglc~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))
```

```{r}
#Extended Data Figure 3e Glu/Gln LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure3de.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(glugln~ Donor + CAR, data=data1)
summary(model)

model <- lmer(glugln~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10a CD25 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10a.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(CD25~ Donor + CAR, data=data1)
summary(model)

model <- lmer(CD25~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10a CD69 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10a.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(CD69~ Donor + CAR, data=data1)
summary(model)

model <- lmer(CD69~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10a CD137 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10a.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(CD137~ Donor + CAR, data=data1)
summary(model)

model <- lmer(CD137~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10a PD1 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10a.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(PD1~ Donor + CAR, data=data1)
summary(model)

model <- lmer(PD1~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10a CTLA4 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10a.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(CTLA4~ Donor + CAR, data=data1)
summary(model)

model <- lmer(CTLA4~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10a LAG3 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10a.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(LAG3~ Donor + CAR, data=data1)
summary(model)

model <- lmer(LAG3~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10a TIM3 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10a.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(TIM3~ Donor + CAR, data=data1)
summary(model)

model <- lmer(TIM3~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10d CD25 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10d.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(CD25~ Donor + CAR, data=data1)
summary(model)

model <- lmer(CD25~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10d CD69 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10d.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(CD69~ Donor + CAR, data=data1)
summary(model)

model <- lmer(CD69~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10d CD137 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10d.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(CD137~ Donor + CAR, data=data1)
summary(model)

model <- lmer(CD137~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10d PD1 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10d.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(PD1~ Donor + CAR, data=data1)
summary(model)

model <- lmer(PD1~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10d CTLA4 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10d.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(CTLA4~ Donor + CAR, data=data1)
summary(model)

model <- lmer(CTLA4~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10d LAG3 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10d.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(LAG3~ Donor + CAR, data=data1)
summary(model)

model <- lmer(LAG3~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```

```{r}
#Extended Data Figure 10d TIM3 LME (Donor Random)

#Load file
data1<- read.csv("~/EDFigure10d.csv", stringsAsFactors = TRUE)

#Change numeric values to character
data1$Donor=as.factor(data1$Donor)

#Add reference
data1$CAR <- relevel(data1$CAR, ref = "EGFRt")

#model data and add optimizer 
model.matrix(~Donor + CAR, data=data1, CAR=EGFRt)
model <- lm(TIM3~ Donor + CAR, data=data1)
summary(model)

model <- lmer(TIM3~ (1|Donor) + CAR, data=data1)
summary(model)

#get_gof(model)
coef(model)
anova(model)
confint(model)
ranef(model)

#r2(model)
model_performance(model)

#lme
p <- plot(model)
print(p)
qqnorm(residuals(model)) # QQplot of normally distributed values
qqline(residuals(model), col ="red") # Add qqline to plot
plot(density(residuals(model)))

```